// <auto-generated />
using System;
using Bus_ticketing_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bus_ticketing_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102125228_FixingBookingEntity")]
    partial class FixingBookingEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bus_ticketingAPI.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PriceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("BookingId");

                    b.HasIndex("BusId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.Bus", b =>
                {
                    b.Property<Guid>("BusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ModelYear")
                        .HasColumnType("integer");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BusId");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            BusId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Capacity = 45,
                            DriverName = "Sami Ahmad",
                            Features = "WiFi,AC,USB Charger",
                            Model = "Mercedes-Benz Travego",
                            ModelYear = 2023,
                            Operator = "JET",
                            Type = "VIP"
                        },
                        new
                        {
                            BusId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Capacity = 50,
                            DriverName = "Omar Khaled",
                            Features = "WiFi,AC,USB Charger,W/C",
                            Model = "Volvo B11R",
                            ModelYear = 2021,
                            Operator = "Hijazi",
                            Type = "Standard"
                        });
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = "LOC_AMN",
                            NameAr = "عمان",
                            NameEn = "Amman"
                        },
                        new
                        {
                            Id = "LOC_IRB",
                            NameAr = "إربد",
                            NameEn = "Irbid"
                        },
                        new
                        {
                            Id = "LOC_ZAR",
                            NameAr = "الزرقاء",
                            NameEn = "Zarqa"
                        },
                        new
                        {
                            Id = "LOC_BAL",
                            NameAr = "البلقاء",
                            NameEn = "Balqa"
                        },
                        new
                        {
                            Id = "LOC_MAD",
                            NameAr = "مأدبا",
                            NameEn = "Madaba"
                        },
                        new
                        {
                            Id = "LOC_KAR",
                            NameAr = "الكرك",
                            NameEn = "Karak"
                        },
                        new
                        {
                            Id = "LOC_TAF",
                            NameAr = "الطفيلة",
                            NameEn = "Tafilah"
                        },
                        new
                        {
                            Id = "LOC_MAA",
                            NameAr = "معان",
                            NameEn = "Ma'an"
                        },
                        new
                        {
                            Id = "LOC_AQA",
                            NameAr = "العقبة",
                            NameEn = "Aqaba"
                        },
                        new
                        {
                            Id = "LOC_AJL",
                            NameAr = "عجلون",
                            NameEn = "Ajloun"
                        },
                        new
                        {
                            Id = "LOC_JER",
                            NameAr = "جرش",
                            NameEn = "Jerash"
                        },
                        new
                        {
                            Id = "LOC_MAF",
                            NameAr = "المفرق",
                            NameEn = "Mafraq"
                        });
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.Routes", b =>
                {
                    b.Property<Guid>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DistanceKm")
                        .HasColumnType("integer");

                    b.Property<double>("DurationHrs")
                        .HasColumnType("double precision");

                    b.Property<string>("OriginId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RouteId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            RouteId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            DestinationId = "LOC_IRB",
                            DistanceKm = 80,
                            DurationHrs = 1.5,
                            OriginId = "LOC_AMN"
                        },
                        new
                        {
                            RouteId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            DestinationId = "LOC_AMN",
                            DistanceKm = 80,
                            DurationHrs = 1.5,
                            OriginId = "LOC_IRB"
                        });
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.Station", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StreetEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CityId = "LOC_AMN",
                            Lat = 31.989999999999998,
                            Lng = 35.909999999999997,
                            NameEn = "Tabarbour",
                            StationName = "North Terminal",
                            StreetEn = "Tareq St"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CityId = "LOC_IRB",
                            Lat = 32.549999999999997,
                            Lng = 35.850000000000001,
                            NameEn = "Irbid City Center",
                            StationName = "Amman Bus Station",
                            StreetEn = "University St"
                        });
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.Trip", b =>
                {
                    b.Property<Guid>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer");

                    b.Property<Guid>("BusId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("time");

                    b.Property<decimal>("PriceJod")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TripId");

                    b.HasIndex("BusId");

                    b.HasIndex("RouteId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AvailableSeats = 45,
                            BusId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            DepartureDate = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 8, 30, 0, 0),
                            PriceJod = 2.50m,
                            RouteId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Status = "Scheduled"
                        },
                        new
                        {
                            TripId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AvailableSeats = 50,
                            BusId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            DepartureDate = new DateTime(2025, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 14, 0, 0, 0),
                            PriceJod = 2.00m,
                            RouteId = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.Booking", b =>
                {
                    b.HasOne("Bus_ticketingAPI.Entities.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bus_ticketingAPI.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bus_ticketingAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.Routes", b =>
                {
                    b.HasOne("Bus_ticketingAPI.Entities.City", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bus_ticketingAPI.Entities.City", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("Origin");
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.Station", b =>
                {
                    b.HasOne("Bus_ticketingAPI.Entities.City", "City")
                        .WithMany("Areas")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.Trip", b =>
                {
                    b.HasOne("Bus_ticketingAPI.Entities.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bus_ticketingAPI.Entities.Routes", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Bus_ticketingAPI.Entities.City", b =>
                {
                    b.Navigation("Areas");
                });
#pragma warning restore 612, 618
        }
    }
}
